apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-data
  namespace: monitoring
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/ubuntu/grafana-data
